"""Añadiendo_esquema_Fase1

Revision ID: 6930fdfd1d97
Revises: 
Create Date: 2026-03-27 11:51:54.501916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6930fdfd1d97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_almacenes_id'), 'almacenes', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('auditoria_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('datos_antes', sa.String(), nullable=True),
    sa.Column('datos_despues', sa.String(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_log_id'), 'auditoria_log', ['id'], unique=False)
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('capacidad_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_id'), 'zonas', ['id'], unique=False)
    op.add_column('movimientos', sa.Column('codigo', sa.String(length=20), nullable=True))
    op.add_column('movimientos', sa.Column('ubicacion_origen_id', sa.Integer(), nullable=True))
    op.add_column('movimientos', sa.Column('ubicacion_destino_id', sa.Integer(), nullable=True))
    op.add_column('movimientos', sa.Column('estado', sa.String(length=20), nullable=True))
    op.add_column('movimientos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'movimientos', ['codigo'])
    op.create_foreign_key(None, 'movimientos', 'ubicaciones', ['ubicacion_origen_id'], ['id'])
    op.create_foreign_key(None, 'movimientos', 'ubicaciones', ['ubicacion_destino_id'], ['id'])
    op.create_foreign_key(None, 'movimientos', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('productos', sa.Column('descripcion', sa.String(length=500), nullable=True))
    op.add_column('productos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('unidad_medida', sa.String(length=20), nullable=True))
    op.add_column('productos', sa.Column('stock_maximo', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('precio_coste', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('productos', sa.Column('codigo_barras', sa.String(length=50), nullable=True))
    op.add_column('productos', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    op.add_column('productos', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('productos', sa.Column('creado_en', sa.DateTime(), nullable=True))
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('productos', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_unique_constraint(None, 'productos', ['codigo_barras'])
    op.create_foreign_key(None, 'productos', 'proveedores', ['proveedor_id'], ['id'])
    op.create_foreign_key(None, 'productos', 'categorias', ['categoria_id'], ['id'])
    op.add_column('stock', sa.Column('lote', sa.String(length=50), nullable=True))
    op.add_column('stock', sa.Column('fecha_caducidad', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('actualizado_en', sa.DateTime(), nullable=True))
    op.alter_column('stock', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    op.add_column('ubicaciones', sa.Column('zona_id', sa.Integer(), nullable=True))
    op.add_column('ubicaciones', sa.Column('descripcion', sa.String(length=200), nullable=True))
    op.add_column('ubicaciones', sa.Column('capacidad_max', sa.Integer(), nullable=True))
    op.add_column('ubicaciones', sa.Column('activo', sa.Boolean(), nullable=True))
    op.alter_column('ubicaciones', 'codigo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_foreign_key(None, 'ubicaciones', 'zonas', ['zona_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ubicaciones', type_='foreignkey')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.alter_column('ubicaciones', 'codigo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('ubicaciones', 'activo')
    op.drop_column('ubicaciones', 'capacidad_max')
    op.drop_column('ubicaciones', 'descripcion')
    op.drop_column('ubicaciones', 'zona_id')
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.alter_column('stock', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('stock', 'actualizado_en')
    op.drop_column('stock', 'fecha_caducidad')
    op.drop_column('stock', 'lote')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='unique')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.alter_column('productos', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('productos', 'nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('productos', 'creado_en')
    op.drop_column('productos', 'activo')
    op.drop_column('productos', 'imagen_url')
    op.drop_column('productos', 'codigo_barras')
    op.drop_column('productos', 'precio_coste')
    op.drop_column('productos', 'stock_maximo')
    op.drop_column('productos', 'unidad_medida')
    op.drop_column('productos', 'proveedor_id')
    op.drop_column('productos', 'categoria_id')
    op.drop_column('productos', 'descripcion')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', type_='unique')
    op.drop_column('movimientos', 'usuario_id')
    op.drop_column('movimientos', 'estado')
    op.drop_column('movimientos', 'ubicacion_destino_id')
    op.drop_column('movimientos', 'ubicacion_origen_id')
    op.drop_column('movimientos', 'codigo')
    op.drop_index(op.f('ix_zonas_id'), table_name='zonas')
    op.drop_table('zonas')
    op.drop_index(op.f('ix_auditoria_log_id'), table_name='auditoria_log')
    op.drop_table('auditoria_log')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_almacenes_id'), table_name='almacenes')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
